### ISSUE TITLE
Install notes

### ISSUE THREAD

**Issue by Nattle** [noahlange/homebrewery-electron#3]
In order to get it to build I had to do the following:

npm install yarn
npm install react@15.6.1
npm install react-dom@15.6.1
npm install typescript
npm install ntypescript
npm install react-codemirror
npm install react-codemirror2
npm install @ types/react

(Note that there shouldn't be a space between @ and types/react but without it git hub thinks it's a name mention.

**Comment by noahlange** [comment]
Oh, you're using NPM. You'll need to run `npm install` before attempting a build. I'll update that for NPM users.

**Comment by noahlange** [comment]
@xCette - updated in commit da4e5f1be3a0d1be993940349bc18474ccf6ac63.

Thanks for taking a look!
